In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,f1_score, precision_score, recall_score, roc_auc_score

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV

import pickle

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
#a

In [12]:
class uji(): 
    def __init__(self,data): 
        df0 = pd.read_csv('../data2_smpl30/uji%snorm.csv'%data, delimiter= ",", header=None)
        df0=df0.fillna(0)
        self.com=df0[0]
        self.prot=df0[1282]
        self.x =df0.drop([0,1282], axis=1)
        df0[1300]=0
        
        self.y=df0[1300]
        self.dt=data
class latih(): 
    def __init__(self,data): 
        df = pd.read_csv("../data2_smpl30/%s.csv"%data, delimiter=',')
        df.head()
        self.X = df.drop(['label'], axis=1)
        self.Y = df['label']
        self.dt=data
class uji3(): 
    def __init__(self,data): 
        df0 = pd.read_csv('../data2_smpl30/%s.csv'%data, delimiter= ";", header=None)
        df0=df0.fillna(0)
        self.com_search=df0[0]
        self.com_id=df0[1]
        self.com=df0[2]
        self.prot=df0[1284]
        self.x =df0.drop([0,1,2,1284], axis=1)
        df0[1300]=0
        
        self.y=df0[1300]
        self.dt=data
def dtuji(data): 
    return uji(data) 
def dtlatih(data): 
    return latih(data) 
def dtuji3(data): 
    return uji3(data) 


dtf =dtuji('mbafika') #dtf.com, dtf.prot, dtf.x, dtf.y, dtf.dt
dtl =dtuji('mbalinda') #dtl.com, dtl.prot, dtl.x, dtl.y dtl.dt
dtg2 = dtuji3('uji_legetan')
dtg3 = dtuji3('uji_inhibitcox2')

In [13]:
dtg =dtuji('gabung') #dtl.com, dtl.prot, dtl.x, dtl.y dtl.dt

In [30]:
dtt =dtuji('tambahan_2')
dtk =dtuji('tambahan_kayuputih')

In [35]:
dtt =dtuji('buyelfie')
dtk =dtuji('herbaldb')

In [28]:
def load_model(model,o):
    rf = pickle.load(open('../data2_smpl30/model/{0}_latih_sampled30_{1}'.format(model,o), 'rb'))
#     print('{0}_latih_sampled30_{1}'.format(model.__name__,o))
#     print('Best parameters found:', rf.best_params_)
#     print('AUC :',rf.cv_results_['mean_test_AUC'])
#     print('Accuracy :',rf.cv_results_['mean_test_Accuracy'])
#     print('F-measure :',rf.cv_results_['mean_test_F-measure'])
#     print('Precision :',rf.cv_results_['mean_test_Precision'])
#     print('Recall :',rf.cv_results_['mean_test_Recall'])
    return rf

In [23]:
class latih(): 
    def __init__(self,data): 
        df = pd.read_csv("../data2_smpl30/%s.csv"%data, delimiter=',')
        df.head()
        self.X = df.drop(['0','1282','0.1'], axis=1)
        self.Y = df['0.1']
        self.dt=data

def dtlatih(data): 
    return latih(data) 
df= dtlatih('latih_sampled30_1') #df1.X,df1.Y,df1.dt

/home/biofarmaka/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3325: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [24]:

def prediksi(md,model,p,data,d):
    pred_x = pd.DataFrame(md.predict_proba(data.x))
    prob_x = pd.DataFrame(np.where(pred_x >= p, 1,0))
    print("threshold {0} ".format(p))
    print("{0}_latih_sampled30_{1} ".format(model,d))
    print("hasil prediksi ",data.dt," : (0,1)")
    print(confusion_matrix(data.y, prob_x[1]))
    pred = pd.DataFrame(prob_x[1])
    pred=pred.drop([0])
    pred[2] = data.com
    pred[3] = data.prot
    #print(pred.head())
    #print(prob_x)
    pred[4] = pred_x[1]
    #print(pred.head())
    #print(pd.DataFrame(prob_x)[1].head())
    pred.to_excel('../data2_smpl30/hasil_pred/{0}_{1}p_{2}_latih_sampled30_{3}.xlsx'.format(model,p,data.dt,d))
from sklearn.decomposition import PCA
pca = PCA(n_components=128)# adjust yourself
pca.fit(df.X)
def prediksi_pca(md,model,p,data,d):
    XX = pca.transform(data.x)
    pred_x = pd.DataFrame(md.predict_proba(XX))
    prob_x = pd.DataFrame(np.where(pred_x >= p, 1,0))
    print("threshold {0} ".format(p))
    print("{0}_latih_sampled30_{1} ".format(model,d))
    print("hasil prediksi ",data.dt," : (0,1)")
    print(confusion_matrix(data.y, prob_x[1]))
    pred = pd.DataFrame(prob_x[1])
    pred=pred.drop([0])
    pred[2] = data.com
    pred[3] = data.prot
    #print(pred.head())
    #print(prob_x)
    pred[4] = pred_x[1]
    #print(pred.head())
    #print(pd.DataFrame(prob_x)[1].head())
    pred.to_excel('../data2_smpl30/hasil_pred/{0}_{1}p_{2}_latih_sampled30_{3}.xlsx'.format(model,p,data.dt,d))
    

In [21]:
def pred3(model,p,datauji1,datauji2,datauji3,d):
    md=load_model(model,d)
    prediksi(md,model,p,datauji1,d)
    prediksi(md,model,p,datauji2,d)
    prediksi(md,model,p,datauji3,d)
def pred2(model,p,datauji1,datauji2,d):
    md=load_model(model,d)
    prediksi(md,model,p,datauji1,d)
    prediksi(md,model,p,datauji2,d)
def pred2_pca(model,p,datauji1,datauji2,d):
    md=load_model(model,d)
    prediksi_pca(md,model,p,datauji1,d)
    prediksi_pca(md,model,p,datauji2,d)
def pred(model,p,datauji1,d):
    md=load_model(model,d)
    prediksi(md,model,p,datauji1,d)

In [36]:
pred2_pca('svm_2',0.5,dtt,dtk,2)
pred2_pca('svm_2',0.5,dtt,dtk,1)
pred2_pca('svm_2',0.5,dtt,dtk,3)
pred2_pca('svm_2',0.5,dtt,dtk,4)
pred2_pca('svm_2',0.5,dtt,dtk,5)

threshold 0.5 
svm_2_latih_sampled30_2 
hasil prediksi  buyelfie  : (0,1)
[[984]]
threshold 0.5 
svm_2_latih_sampled30_2 
hasil prediksi  herbaldb  : (0,1)
[[6488]]
threshold 0.5 
svm_2_latih_sampled30_1 
hasil prediksi  buyelfie  : (0,1)
[[983   1]
 [  0   0]]
threshold 0.5 
svm_2_latih_sampled30_1 
hasil prediksi  herbaldb  : (0,1)
[[6487    1]
 [   0    0]]
threshold 0.5 
svm_2_latih_sampled30_3 
hasil prediksi  buyelfie  : (0,1)
[[984]]
threshold 0.5 
svm_2_latih_sampled30_3 
hasil prediksi  herbaldb  : (0,1)
[[6488]]
threshold 0.5 
svm_2_latih_sampled30_4 
hasil prediksi  buyelfie  : (0,1)
[[984]]
threshold 0.5 
svm_2_latih_sampled30_4 
hasil prediksi  herbaldb  : (0,1)
[[6488]]
threshold 0.5 
svm_2_latih_sampled30_5 
hasil prediksi  buyelfie  : (0,1)
[[984]]
threshold 0.5 
svm_2_latih_sampled30_5 
hasil prediksi  herbaldb  : (0,1)
[[6488]]


In [25]:
pred2_pca('svm_2',0.5,dtg2,dtg3,2)
pred2_pca('svm_2',0.5,dtg2,dtg3,1)
pred2_pca('svm_2',0.5,dtg2,dtg3,3)
pred2_pca('svm_2',0.5,dtg2,dtg3,4)
pred2_pca('svm_2',0.5,dtg2,dtg3,5)

threshold 0.5 
svm_2_latih_sampled30_2 
hasil prediksi  uji_legetan  : (0,1)
[[3809]]
threshold 0.5 
svm_2_latih_sampled30_2 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
svm_2_latih_sampled30_1 
hasil prediksi  uji_legetan  : (0,1)
[[3809]]
threshold 0.5 
svm_2_latih_sampled30_1 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
svm_2_latih_sampled30_3 
hasil prediksi  uji_legetan  : (0,1)
[[3809]]
threshold 0.5 
svm_2_latih_sampled30_3 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
svm_2_latih_sampled30_4 
hasil prediksi  uji_legetan  : (0,1)
[[3809]]
threshold 0.5 
svm_2_latih_sampled30_4 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
svm_2_latih_sampled30_5 
hasil prediksi  uji_legetan  : (0,1)
[[3809]]
threshold 0.5 
svm_2_latih_sampled30_5 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]


In [37]:
pred2('rf',0.5,dtt,dtk,2)
pred2('rf',0.5,dtt,dtk,1)
pred2('rf',0.5,dtt,dtk,3)
pred2('rf',0.5,dtt,dtk,4)
pred2('rf',0.5,dtt,dtk,5)

threshold 0.5 
rf_latih_sampled30_2 
hasil prediksi  buyelfie  : (0,1)
[[497 487]
 [  0   0]]
threshold 0.5 
rf_latih_sampled30_2 
hasil prediksi  herbaldb  : (0,1)
[[3854 2634]
 [   0    0]]
threshold 0.5 
rf_latih_sampled30_1 
hasil prediksi  buyelfie  : (0,1)
[[500 484]
 [  0   0]]
threshold 0.5 
rf_latih_sampled30_1 
hasil prediksi  herbaldb  : (0,1)
[[4174 2314]
 [   0    0]]
threshold 0.5 
rf_latih_sampled30_3 
hasil prediksi  buyelfie  : (0,1)
[[516 468]
 [  0   0]]
threshold 0.5 
rf_latih_sampled30_3 
hasil prediksi  herbaldb  : (0,1)
[[4377 2111]
 [   0    0]]
threshold 0.5 
rf_latih_sampled30_4 
hasil prediksi  buyelfie  : (0,1)
[[504 480]
 [  0   0]]
threshold 0.5 
rf_latih_sampled30_4 
hasil prediksi  herbaldb  : (0,1)
[[4212 2276]
 [   0    0]]
threshold 0.5 
rf_latih_sampled30_5 
hasil prediksi  buyelfie  : (0,1)
[[504 480]
 [  0   0]]
threshold 0.5 
rf_latih_sampled30_5 
hasil prediksi  herbaldb  : (0,1)
[[4163 2325]
 [   0    0]]


In [26]:
pred2('rf',0.5,dtg2,dtg3,2)
pred2('rf',0.5,dtg2,dtg3,1)
pred2('rf',0.5,dtg2,dtg3,3)
pred2('rf',0.5,dtg2,dtg3,4)
pred2('rf',0.5,dtg2,dtg3,5)

threshold 0.5 
rf_latih_sampled30_2 
hasil prediksi  uji_legetan  : (0,1)
[[3809]]
threshold 0.5 
rf_latih_sampled30_2 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
rf_latih_sampled30_1 
hasil prediksi  uji_legetan  : (0,1)
[[3809]]
threshold 0.5 
rf_latih_sampled30_1 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
rf_latih_sampled30_3 
hasil prediksi  uji_legetan  : (0,1)
[[3807    2]
 [   0    0]]
threshold 0.5 
rf_latih_sampled30_3 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
rf_latih_sampled30_4 
hasil prediksi  uji_legetan  : (0,1)
[[3806    3]
 [   0    0]]
threshold 0.5 
rf_latih_sampled30_4 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]
threshold 0.5 
rf_latih_sampled30_5 
hasil prediksi  uji_legetan  : (0,1)
[[3806    3]
 [   0    0]]
threshold 0.5 
rf_latih_sampled30_5 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2637]]


In [38]:
pred2('mlp',0.5,dtt,dtk,2)
pred2('mlp',0.5,dtt,dtk,1)
pred2('mlp',0.5,dtt,dtk,3)
pred2('mlp',0.5,dtt,dtk,4)
pred2('mlp',0.5,dtt,dtk,5)

threshold 0.5 
mlp_latih_sampled30_2 
hasil prediksi  buyelfie  : (0,1)
[[556 428]
 [  0   0]]
threshold 0.5 
mlp_latih_sampled30_2 
hasil prediksi  herbaldb  : (0,1)
[[4045 2443]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_1 
hasil prediksi  buyelfie  : (0,1)
[[584 400]
 [  0   0]]
threshold 0.5 
mlp_latih_sampled30_1 
hasil prediksi  herbaldb  : (0,1)
[[3846 2642]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_3 
hasil prediksi  buyelfie  : (0,1)
[[658 326]
 [  0   0]]
threshold 0.5 
mlp_latih_sampled30_3 
hasil prediksi  herbaldb  : (0,1)
[[4869 1619]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_4 
hasil prediksi  buyelfie  : (0,1)
[[761 223]
 [  0   0]]
threshold 0.5 
mlp_latih_sampled30_4 
hasil prediksi  herbaldb  : (0,1)
[[4957 1531]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_5 
hasil prediksi  buyelfie  : (0,1)
[[679 305]
 [  0   0]]
threshold 0.5 
mlp_latih_sampled30_5 
hasil prediksi  herbaldb  : (0,1)
[[4820 1668]
 [   0    0]]


In [17]:
pred2('mlp',0.5,dtg2,dtg3,2)
pred2('mlp',0.5,dtg2,dtg3,1)
pred2('mlp',0.5,dtg2,dtg3,3)
pred2('mlp',0.5,dtg2,dtg3,4)
pred2('mlp',0.5,dtg2,dtg3,5)

threshold 0.5 
mlp_latih_sampled30_2 
hasil prediksi  uji_legetan  : (0,1)
[[3727   82]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_2 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2507  130]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_1 
hasil prediksi  uji_legetan  : (0,1)
[[3668  141]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_1 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2515  122]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_3 
hasil prediksi  uji_legetan  : (0,1)
[[3723   86]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_3 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2619   18]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_4 
hasil prediksi  uji_legetan  : (0,1)
[[3650  159]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_4 
hasil prediksi  uji_inhibitcox2  : (0,1)
[[2517  120]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_5 
hasil prediksi  uji_legetan  : (0,1)
[[3743   66]
 [   0    0]]
threshold 0.5 
mlp_latih_sampled30_5 
hasil prediksi  uji_inhibitc

In [48]:
pred3('mlp',0.5,dtf,dtl,dtt,5)

threshold 0.5 
mlp_hasilsmote_5 
hasil prediksi  mbafika  : (0,1)
[[194  46]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_5 
hasil prediksi  mbalinda  : (0,1)
[[2285  763]
 [   0    0]]
threshold 0.5 
mlp_hasilsmote_5 
hasil prediksi  tambahan  : (0,1)
[[14 10]
 [ 0  0]]


In [52]:
scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy','F-measure':'f1','Precision':'precision', 'Recall':'recall'}


In [49]:
from sklearn import svm

In [9]:
pred3('svm_rbf',0.5,dtf,dtl,dtt,5)

threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  mbafika  : (0,1)
[[240]]
threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  mbalinda  : (0,1)
[[2941  107]
 [   0    0]]
threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  tambahan  : (0,1)
[[16  8]
 [ 0  0]]


In [10]:
pred3('svm_rbf',0.5,dtf,dtl,dtt,4)
pred3('svm_rbf',0.5,dtf,dtl,dtt,3)
pred3('svm_rbf',0.5,dtf,dtl,dtt,2)
pred3('svm_rbf',0.5,dtf,dtl,dtt,1)

D:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.svm.classes module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.svm. Anything that cannot be imported from sklearn.svm is now part of the private API.
  warnings.warn(message, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator SVC from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


AttributeError: 'SVC' object has no attribute '_n_support'

In [11]:
pred3('rf_100n_1000m',0.5,dtf,dtl,dtt,4)
pred3('rf_100n_1000m',0.5,dtf,dtl,dtt,3)
pred3('rf_100n_1000m',0.5,dtf,dtl,dtt,2)
pred3('rf_100n_1000m',0.5,dtf,dtl,dtt,1)
pred3('rf_100n_1000m',0.5,dtf,dtl,dtt,5)

D:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.ensemble.bagging module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.tree.tree module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid res

threshold 0.5 
rf_100n_1000m_hasilsmote_4 
hasil prediksi  mbafika  : (0,1)
[[120 120]
 [  0   0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_4 
hasil prediksi  mbalinda  : (0,1)
[[1530 1518]
 [   0    0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_4 
hasil prediksi  tambahan  : (0,1)
[[12 12]
 [ 0  0]]


D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator BaggingClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


threshold 0.5 
rf_100n_1000m_hasilsmote_3 
hasil prediksi  mbafika  : (0,1)
[[120 120]
 [  0   0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_3 
hasil prediksi  mbalinda  : (0,1)
[[1563 1485]
 [   0    0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_3 
hasil prediksi  tambahan  : (0,1)
[[12 12]
 [ 0  0]]


D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator BaggingClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


threshold 0.5 
rf_100n_1000m_hasilsmote_2 
hasil prediksi  mbafika  : (0,1)
[[120 120]
 [  0   0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_2 
hasil prediksi  mbalinda  : (0,1)
[[1526 1522]
 [   0    0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_2 
hasil prediksi  tambahan  : (0,1)
[[12 12]
 [ 0  0]]


D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator BaggingClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


threshold 0.5 
rf_100n_1000m_hasilsmote_1 
hasil prediksi  mbafika  : (0,1)
[[144  96]
 [  0   0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_1 
hasil prediksi  mbalinda  : (0,1)
[[1755 1293]
 [   0    0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_1 
hasil prediksi  tambahan  : (0,1)
[[12 12]
 [ 0  0]]


D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator BaggingClassifier from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
D:\Anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.21.2 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


threshold 0.5 
rf_100n_1000m_hasilsmote_5 
hasil prediksi  mbafika  : (0,1)
[[123 117]
 [  0   0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_5 
hasil prediksi  mbalinda  : (0,1)
[[1773 1275]
 [   0    0]]
threshold 0.5 
rf_100n_1000m_hasilsmote_5 
hasil prediksi  tambahan  : (0,1)
[[13 11]
 [ 0  0]]
